{% set name = "sella" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Sella-{{ version }}.tar.gz
  sha256: c6d5718ec6edb7e70850d51896e1bda2c3e7fe3a7017057dd95c7b5d876c17d4

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - ase >=3.18.0
    - jax >=0.2.3
    - jaxlib >=0.1.56
    - {{ pin_compatible('numpy') }}
    - python
    - scipy >=1.1.0

test:
  imports:
    - sella
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Sella/
  doc_url: https://github.com/zadorlab/sella/wiki
  summary: |
    Sella is a utility for finding first order saddle points
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
