{% set name = "sella" %}
{% set version = "2.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2340eea946c936b24ed918713d5448f9ca76f5a4ea28be9aa6e11eb91b96c372

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - ase >=3.18.0
    - jax >=0.2.3
    - jaxlib >=0.1.56
    - {{ pin_compatible('numpy') }}
    - python
    - scipy >=1.1.0

test:
  imports:
    - sella
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Sella/
  doc_url: https://github.com/zadorlab/sella/wiki
  summary: |
    Sella is a utility for finding first order saddle points
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
